<?php
	$banner_image = "../CacheCrashCourse/cpu_monochromatic.svg";
	$banner_classes = "banner-fit";
	$banner_alt = "An illustration of a CPU";
	$publish_date = "2020/06/30";
	$post_title = "Cache Crash Course - Compiler edge cases (Part 5)";
	$synopsis = "Part five of our deep dive into the CPU cache and how to optimize for it. Part five explores how seemingly small changes can change the performance in non-trivial ways by looking at some edge cases with instructions generated by compilers.";
	$image_credits = [
		"CPU illustration" => ["Many Pixels", "https://www.manypixels.co/" ]
	];
	
	if(isset($is_header)){ return; }
	
	$use_prism = true;
	$use_chartjs = true;
	$use_jsdiff = false;
	
	include '../../components/blog_post_header.php'
?>

<p><b>New here?</b> Here's <a href="/Blog/CacheCrashCourse/">part one</a>, which you should read first if you haven't already.</p>

<p>WIP</p>

<?php Chart( "msvc_chart.json", "Benchmark results for MSVC" ); ?>

<?php Chart( "clang_chart.json", "Benchmark results for Clang" ); ?>

<?php Chart( "gcc_chart.json", "Benchmark results for GCC" ); ?>

<?php Chart( "msvc_vs_clang_chart.json", "MSVC vs Clang" ); ?>

<p></p><br />

<p><b>Nearly there! Want to go to <a href="/Blog/CacheCrashCourse6/">part six - the dramatic conclusion?</a></p>

<a href="/Blog/CacheCrashCourse6/" class="btn">Part six</a>

<p></p>

<?php include '../../components/blog_post_footer.php' ?>